apiVersion: apps/v1                 
kind: Deployment                    
metadata:
  name: litehrnet-deployment                   
  labels:                          
    app: litehrnet-app                   
spec:
  replicas: 2                      
  selector:
    matchLabels:
      app: litehrnet-app                  
  template:
    metadata:
      labels:
        app: litehrnet-app               
    spec:
      containers:
      - name: tiviluson-litehrnet   
        image: tiviluson/litehrnet_onnx:v0.3
        ports:                        
        - containerPort: 8000          
          name: uvicorn-port        
  strategy:
    type: RollingUpdate          
    rollingUpdate:
      maxSurge: 1                 
      maxUnavailable: 1           